FROM golang:1.11.5

# Getting ready:
#RUN apt-get update
#RUN apt-get -y upgrade
#RUN apt-get -y install curl git

ENV GOROOT=/usr/local/go

# goreleaser
RUN curl -L https://github.com/goreleaser/goreleaser/releases/download/v0.101.0/goreleaser_Linux_x86_64.tar.gz | tar zx -C /usr/local/bin/
